/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  env: {
    DB_CONNECTION_STRING: process.env.DB_CONNECTION_STRING,
    STRIPE_PUBLISHABLE_KEY_TEST: process.env.STRIPE_PUBLISHABLE_KEY_TEST,
    STRIPE_SECRET_KEY_TEST: process.env.STRIPE_SECRET_KEY_TEST,
    STRIPE_WEBHOOK_SECRET_TEST: process.env.STRIPE_WEBHOOK_SECRET_TEST,
    STRIPE_FREE_SHIPPING_TEST: process.env.STRIPE_FREE_SHIPPING_TEST,
    STRIPE_PUBLISHABLE_KEY_PROD: process.env.STRIPE_PUBLISHABLE_KEY_PROD,
    STRIPE_SECRET_KEY_PROD: process.env.STRIPE_SECRET_KEY_PROD,
    STRIPE_WEBHOOK_SECRET_PROD: process.env.STRIPE_WEBHOOK_SECRET_PROD,
    STRIPE_FREE_SHIPPING_PROD: process.env.STRIPE_FREE_SHIPPING_PROD,
  },
};

module.exports = nextConfig;
